spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
      max-lifetime: 120000
      pool-name: customers-mysql-pool
    url: 'jdbc:mysql://${DB_HOST}?serverTimezone=America/Sao_Paulo'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
security:
  jwt:
    secret-key: ${SECRET}
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"